Python中的异常处理是通过 `try`、`except`、`else` 和 `finally` 语句来实现的，这些结构提供了强大的错误管理和程序恢复机制。

## 基本结构

**Python中的异常都是类，继承自 `BaseException` 类。最常用的异常基类是 `Exception`。**

`try`: 尝试执行的代码块，可能抛出异常的部分。
`except`: 当 `try块`中发生异常时执行的代码块。可以指定一个或多个` except子句` 来捕获不同类型的异常。
`else`: 如果 `try块`没有引发异常，则执行这里的代码。这提供了在没有异常情况下执行某些操作的途径。
`finally`: 不管是否发生异常，都会执行这里的代码。通常用于清理资源，如关闭文件。

```python
try:
    # 尝试执行的代码
    result = 10 / 0  # 这里会抛出ZeroDivisionError
except ZeroDivisionError:
    # 处理特定异常
    print("不能除以零！")
except Exception as e:
    # 处理其他所有异常
    print(f"发生了异常: {e}")
else:
    # 如果没有异常发生，执行这里的代码
    print("一切正常！")
finally:
    # 无论是否发生异常，都会执行
    print("清理工作完成。")
```
### 捕获多个异常

可以用元组列出多个异常类型在一个 `except` 子句中。

```python
except (TypeError, ValueError) as e:
    print("类型错误或值错误:", e)
```

- **`as`关键字**：在except子句中，可以使用`as`关键字来**绑定异常实例到一个变量**，以便获取更多关于异常的信息。
- **`raise`**：**主动抛出异常**，可以自定义异常或重新抛出捕获的异常。
	```python
	raise ValueError("这是一个自定义错误信息。")
	```

### `assert`

用于调试，检测条件是否满足，如果不满足则抛出 `AssertionError`。

```python
assert x > 0, "x必须大于0"
```